### ISSUE TITLE
Work better against huge directories

### ISSUE THREAD

**Issue by simonw** [simonw/symbex#15]
I tried running `symbex '*.*'` in a top-level folder and there was a long delay before it started doing anything.

This is because of this code:

https://github.com/simonw/symbex/blob/b0024829e1b4b2bf29698064d62efbb5e5ec072b/symbex/cli.py#L81-L83

There's no need to wait for the `rglob("*.py")` to finish running before starting work - it would be more efficient as a generator.

**Comment by simonw** [comment]
Now when I run `symbex '*.*'` in a directory with many subdirectories (like `~/Dropbox/Development` on my laptop) it starts outputting results straight away and streams for a long time.

**Comment by spookylukey** [comment]
@simonw I certainly understand the desire to have few dependencies!

I'm also open to extracting the .gitignore stuff as a library. That kind of thing might be better done when I've got at least two projects that need the functionality, to be sure the API works, but now I do.

I'm building on top [pathspec](https://pypi.org/project/pathspec/), but adding a significant amount  - it is particularly nasty because of the way that .gitignore files can be in any directory, and you want to avoid even looking at them if you don't recurse into the directory, and you also need to include the ones in parent directories, without re-doing work. So this imposes a fairly tight structure on the way the directory traversal has to work.
